# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sunmoonlake.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(752, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.btn_Run = QtGui.QPushButton(self.centralwidget)
        self.btn_Run.setGeometry(QtCore.QRect(480, 410, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Run.setFont(font)
        self.btn_Run.setObjectName(_fromUtf8("btn_Run"))
        self.dbox_Local = QtGui.QComboBox(self.centralwidget)
        self.dbox_Local.setGeometry(QtCore.QRect(150, 170, 221, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbox_Local.sizePolicy().hasHeightForWidth())
        self.dbox_Local.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbox_Local.setFont(font)
        self.dbox_Local.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dbox_Local.setAcceptDrops(False)
        self.dbox_Local.setObjectName(_fromUtf8("dbox_Local"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 210, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.rbtn_Morning = QtGui.QRadioButton(self.groupBox)
        self.rbtn_Morning.setGeometry(QtCore.QRect(20, 30, 98, 19))
        self.rbtn_Morning.setChecked(True)
        self.rbtn_Morning.setObjectName(_fromUtf8("rbtn_Morning"))
        self.rbtn_Afternoon = QtGui.QRadioButton(self.groupBox)
        self.rbtn_Afternoon.setGeometry(QtCore.QRect(120, 30, 98, 19))
        self.rbtn_Afternoon.setObjectName(_fromUtf8("rbtn_Afternoon"))
        self.rbtn_Evening = QtGui.QRadioButton(self.groupBox)
        self.rbtn_Evening.setGeometry(QtCore.QRect(220, 30, 98, 19))
        self.rbtn_Evening.setObjectName(_fromUtf8("rbtn_Evening"))
        self.calendarWidget = QtGui.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(400, 10, 296, 194))
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(200, 110, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.timeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(230, 410, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.timeEdit.setFont(font)
        self.timeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(21, 58, 0)))
        self.timeEdit.setDate(QtCore.QDate(2010, 1, 1))
        self.timeEdit.setTime(QtCore.QTime(21, 58, 0))
        self.timeEdit.setMinimumTime(QtCore.QTime(12, 0, 0))
        self.timeEdit.setCurrentSection(QtGui.QDateTimeEdit.MinuteSection)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setCurrentSectionIndex(2)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 450, 681, 91))
        self.scrollArea.setFrameShape(QtGui.QFrame.WinPanel)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 656, 87))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 30, 141, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 70, 141, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 410, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 290, 681, 111))
        self.listWidget.setFrameShape(QtGui.QFrame.WinPanel)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 240, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 30, 58, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 70, 58, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAccessibleDescription(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 120, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 170, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "場地自動租借(試用)", None))
        self.btn_Run.setText(_translate("MainWindow", "執行排程", None))
        self.groupBox.setTitle(_translate("MainWindow", "時段", None))
        self.rbtn_Morning.setText(_translate("MainWindow", "上午", None))
        self.rbtn_Afternoon.setText(_translate("MainWindow", "下午", None))
        self.rbtn_Evening.setText(_translate("MainWindow", "晚上", None))
        self.label.setText(_translate("MainWindow", "排程時間：", None))
        self.pushButton.setText(_translate("MainWindow", "加入排程清單", None))
        self.label_2.setText(_translate("MainWindow", "帳號：", None))
        self.label_3.setText(_translate("MainWindow", "密碼：", None))
        self.label_4.setText(_translate("MainWindow", "日期：", None))
        self.label_5.setText(_translate("MainWindow", "地點：", None))

